---
title: "progress-report-Nicholas-Wang"
author: "Nicholas Wang"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
url <- 'https://www.baseball-reference.com/awards/hof_2023.shtml'
```

```{r}
library(rvest)
html <- read_html(url)
```

```{r}
library(tidyverse)
tables <- html %>% html_table(fill=TRUE)
tables 
```


```{r}
scraped <- tables[[1]]
scraped


```

```{r}
colnames(scraped) <- c("playerID", "yearID", "votedBy", "ballots", "needed", "votes", "inducted", "category", "needed_note")
scraped_data=scraped[-1,]

scraped_data
```
```{r}

scraped_data$votes=scraped_data$ballots
scraped_data$playerID=scraped_data$yearID
scraped_data$yearID=2023
scraped_data$category='Player'
scraped_data$needed_note=NA
scraped_data$votedBy='BBWAA'
scraped_data$ballots=389
scraped_data$needed=292
scraped_data$inducted <- ifelse(scraped_data$votes > scraped_data$needed, "Y", "N")

scraped_data

```


```{r}
scraped_data <- scraped_data[, 1:9]

scraped_data <- scraped_data %>%
  mutate(playerID = str_replace(playerID, "^X-", ""))

scraped_data$playerID[2] <- "Todd Helton"
scraped_data$playerID[6] <- "Carlos Beltran"
scraped_data$playerID[15] <- "Francisco Rodriguez"

scraped_data
```


```{r}

library(Lahman)
people_data <- Lahman::People %>%
  mutate(full_name = paste(nameFirst, nameLast, sep = " "))

matched_data <- left_join(scraped_data, people_data, by = c("playerID" = "full_name")) %>%
  select(playerID.y)  

colnames(matched_data) <- "playerID"
matched_data=matched_data[-15,]
scraped_data$playerID=matched_data$playerID
scraped_data$playerID[21]='dickera01'
scraped_data$playerID[23]='hardyjj01'

scraped_data

HallOfFame <- rbind(HallOfFame, scraped_data)
tail(HallOfFame)

```
